### ISSUE TITLE
ESLint rules not validating

### ISSUE THREAD

**Issue by bdsoha** [cancerberoSgx/jsdoc-typeof-plugin#1]
eslint `types` do not recognize `typeof`, therefore all doc-blocks that utilize the syntax are considered invalid.

**Comment by cancerberoSgx** [comment]
what do you mean by "eslint types" ? For TypeScript what I'm using is tslint (https://palantir.github.io/tslint/ ) instead of eslint and as far as I know it works fine with @typeof . Could you please share a link to that technology? Thanks

**Comment by bdsoha** [comment]
Maybe I wasn't clear with my explanation. I am using vanilla JS and have a problem that `eslint` with the [`valid-jsdoc`](https://eslint.org/docs/rules/valid-jsdoc) rule applied looks through and tries to validate `DocBlocks`. 

It fails to recognize `typeof` as a valid type and generates an error for the `valid-jsdoc` rule, for example:
```
/**
 * @param {typeof SomeClass}
 */
```
